// Precomputed learned patterns extracted from historical municipal correction letters under NBC 2016.
// These represent reviewer behavior patterns — the "code says X, reviewers actually enforce Y" insights.
// In production this would be generated by the Historical Pattern Agent from real letters.
// Source letters: cl-001 through cl-010 in correction-letters.ts

export interface LearnedPattern {
  id: string;
  title: string;
  description: string;
  enforcementBehavior: string;
  codeReference: string;
  confidenceLevel: number; // 0-1
  evidenceCount: number; // how many historical letters support this
  patternType: "stricter_than_code" | "lenient_than_code" | "consistent_with_code";
  sourceCases: string[];
}

export const LEARNED_PATTERNS: LearnedPattern[] = [
  {
    id: "lp-001",
    title: "Egress Window Width — Strict Enforcement, No Rounding",
    description:
      "Municipal reviewers strictly enforce the 500 mm (20-inch) net clear window width with no tolerance for rounding. Windows within 12 mm (0.5 inch) of the minimum (e.g., 488 mm / 19.5 inches) are flagged for correction, not waived.",
    enforcementBehavior:
      "Any egress window under 500 mm (20.0 inches) net clear width is flagged — even if within 12 mm. Reviewers request manufacturer BIS/ISO test certificates and do not accept contractor field measurements.",
    codeReference: "NBC 2016 Part 4, Clause 4.10 & Part 8 Sec 1, Clause 9.11.2 (min 500 mm / 20\" net clear width)",
    confidenceLevel: 0.95,
    evidenceCount: 3,
    patternType: "stricter_than_code",
    sourceCases: ["BPR-2023-0041", "BPR-2023-0134", "BPR-2023-0198"],
  },
  {
    id: "lp-002",
    title: "Side Setback Waivers — Consistently Granted Under 150 mm (6 Inches)",
    description:
      "Reviewers consistently grant administrative waivers for side open space encroachments under 150 mm (6 inches / 0.5 ft) under NBC 2016 Part 2, Clause 12.5 with a licensed surveyor plan. The waiver is processed under standard administrative sanction.",
    enforcementBehavior:
      "Side setback encroachments under 150 mm (6 inches): administrative tolerance waiver granted with registered surveyor demarcation. Encroachments exceeding 150 mm: formal Planning Authority variance required.",
    codeReference:
      "NBC 2016 Part 3, Clause 8.2.3 (1.8 m / 6 ft min) + Part 2, Clause 12.5 (admin waiver up to 150 mm / 6\")",
    confidenceLevel: 0.92,
    evidenceCount: 3,
    patternType: "lenient_than_code",
    sourceCases: ["BPR-2023-0089", "BPR-2024-0012", "BPR-2024-0112"],
  },
  {
    id: "lp-003",
    title: "Sill Height — Exceedances Above 1100 mm Are Strictly Flagged",
    description:
      "Reviewers flag sill height violations even when the exceedance is 25 mm (1 inch) or less. No informal tolerance observed — the 1100 mm (44-inch) maximum is treated as a hard ceiling.",
    enforcementBehavior:
      "Sill heights above 1100 mm (44 inches) are always flagged, regardless of how small the exceedance. An 1125 mm sill generates the same correction notice as a 1250 mm sill.",
    codeReference: "NBC 2016 Part 4, Clause 4.10.1 (maximum 1100 mm / 44\" sill height)",
    confidenceLevel: 0.88,
    evidenceCount: 2,
    patternType: "consistent_with_code",
    sourceCases: ["BPR-2023-0041", "BPR-2024-0156"],
  },
  {
    id: "lp-004",
    title: "Smoke Alarm — Habitable Rooms Always Trigger Interconnect Requirement",
    description:
      "Any application that creates a new habitable room or sleeping room triggers a correction for missing interconnected smoke/heat detection documentation under NBC 2016 Part 4 Table 7.",
    enforcementBehavior:
      "Reviewers require an explicit electrical schematic and detection layout showing interconnected alarms for all habitable rooms. Absence of this generates a mandatory correction item.",
    codeReference: "NBC 2016 Part 4, Clause 4.17 & Table 7 (interconnected detection schedule)",
    confidenceLevel: 0.85,
    evidenceCount: 2,
    patternType: "stricter_than_code",
    sourceCases: ["BPR-2024-0112", "BPR-2023-0198"],
  },
  {
    id: "lp-005",
    title: "Rear Setback Near-Miss — Informational Notation, No Correction",
    description:
      "When a rear open space is compliant but within 300 mm (1 foot) of the required 7.5 m (25 ft), reviewers add an informational note warning the applicant about future addition constraints without delaying sanction.",
    enforcementBehavior:
      "Rear open space within 300 mm of the 7.5 m (25-ft) minimum receives an informational note on the sanction order. This does not constitute a blocking objection.",
    codeReference: "NBC 2016 Part 3, Clause 8.2.2 (7.5 m / 25-ft rear open space)",
    confidenceLevel: 0.75,
    evidenceCount: 1,
    patternType: "lenient_than_code",
    sourceCases: ["BPR-2024-0156"],
  },
  {
    id: "lp-006",
    title: "Exit Door Width — Net Clear Opening Required (1000 mm / 1.0 m)",
    description:
      "Reviewers calculate net clear door opening width after deducting frame rebates — an undersized doorway (e.g., 750 mm clear) is flagged against the NBC 2016 1000 mm (1.0 m) clear requirement.",
    enforcementBehavior:
      "Net clear passage width, not structural masonry rough opening, is verified. A 750 mm clear door is flagged; a 1000 mm clear exit door is the standard requirement.",
    codeReference: "NBC 2016 Part 4, Clause 4.4.2 (1000 mm / 1.0 m min clear door width)",
    confidenceLevel: 0.9,
    evidenceCount: 1,
    patternType: "stricter_than_code",
    sourceCases: ["BPR-2024-0203"],
  },
];

export const PATTERN_COUNT = LEARNED_PATTERNS.length;
export const PATTERN_SOURCE_LETTER_COUNT = 10; // total letters analyzed
