// Precomputed learned patterns extracted from Maplewood Township's historical correction letters.
// These represent reviewer behavior patterns — the "code says X, reviewers actually enforce Y" insights.
// In production this would be generated by the Historical Pattern Agent from real letters.
// Source letters: cl-001 through cl-010 in correction-letters.ts

export interface LearnedPattern {
  id: string;
  title: string;
  description: string;
  enforcementBehavior: string;
  codeReference: string;
  confidenceLevel: number; // 0-1
  evidenceCount: number; // how many historical letters support this
  patternType: "stricter_than_code" | "lenient_than_code" | "consistent_with_code";
  sourceCases: string[];
}

export const LEARNED_PATTERNS: LearnedPattern[] = [
  {
    id: "lp-001",
    title: "Egress Window Width — Strict Enforcement, No Rounding",
    description:
      "Maplewood reviewers strictly enforce the 20-inch net clear window width with no tolerance for rounding. Windows within 0.5 inches of the minimum (e.g., 19.5 inches) are flagged for correction, not waived.",
    enforcementBehavior:
      "Any egress window under 20.0 inches net clear width is flagged — even if within 0.5 inches. Reviewers request manufacturer spec sheets and do not accept contractor field measurements.",
    codeReference: "Section 101.2 (minimum 20-inch net clear width)",
    confidenceLevel: 0.95,
    evidenceCount: 3,
    patternType: "stricter_than_code",
    sourceCases: ["BPR-2023-0041", "BPR-2023-0134", "BPR-2023-0198"],
  },
  {
    id: "lp-002",
    title: "Side Setback Waivers — Consistently Granted Under 6 Inches",
    description:
      "Reviewers consistently grant administrative waivers for side setback encroachments under 6 inches (0.5 ft) with a certified survey. The waiver language is boilerplate — no case-by-case evaluation of impact appears to occur for sub-6-inch encroachments.",
    enforcementBehavior:
      "Side setback encroachments under 6 inches: administrative waiver granted automatically with survey. Encroachments at or over 6 inches (0.5 ft): formal variance required, permit cannot be issued.",
    codeReference:
      "Section 201.3 (6-ft minimum) + Section 201.8 (admin waiver up to 6 inches)",
    confidenceLevel: 0.92,
    evidenceCount: 3,
    patternType: "lenient_than_code",
    sourceCases: ["BPR-2023-0089", "BPR-2024-0012", "BPR-2024-0112"],
  },
  {
    id: "lp-003",
    title: "Sill Height — 1-Inch Exceedances Are Flagged",
    description:
      "Reviewers flag sill height violations even when the exceedance is 1 inch or less. No informal tolerance observed — the 44-inch maximum is treated as a hard ceiling.",
    enforcementBehavior:
      "Sill heights above 44 inches are always flagged, regardless of how small the exceedance. A 45-inch sill generates the same correction notice as a 50-inch sill.",
    codeReference: "Section 101.2 (maximum 44-inch sill height)",
    confidenceLevel: 0.88,
    evidenceCount: 2,
    patternType: "consistent_with_code",
    sourceCases: ["BPR-2023-0041", "BPR-2024-0156"],
  },
  {
    id: "lp-004",
    title: "Smoke Alarm — New Sleeping Rooms Always Trigger Interconnect Requirement",
    description:
      "Any application that creates a new sleeping room (addition or conversion) triggers a correction for missing interconnected smoke alarm documentation, even when the existing dwelling may have standalone alarms.",
    enforcementBehavior:
      "Reviewers require an explicit smoke alarm location plan and wiring diagram showing interconnection for any new sleeping room. Absence of this from the plans always generates a correction item.",
    codeReference: "Section 101.9 (interconnected smoke alarms for new sleeping rooms)",
    confidenceLevel: 0.85,
    evidenceCount: 2,
    patternType: "stricter_than_code",
    sourceCases: ["BPR-2024-0112", "BPR-2023-0198"],
  },
  {
    id: "lp-005",
    title: "Rear Setback Near-Miss — Informational Notation, No Correction",
    description:
      "When a rear setback is compliant but within 1 foot of the minimum, reviewers add an informational note to the record warning the applicant about future addition constraints — but this is noted, not flagged as a violation.",
    enforcementBehavior:
      "Rear setbacks within 1 foot of the 25-foot minimum receive a written informational note. This does not constitute a correction item and does not delay permit issuance.",
    codeReference: "Section 201.4 (25-ft rear setback minimum)",
    confidenceLevel: 0.75,
    evidenceCount: 1,
    patternType: "lenient_than_code",
    sourceCases: ["BPR-2024-0156"],
  },
  {
    id: "lp-006",
    title: "Primary Exit Door Width — Strict Net Clear Measurement",
    description:
      "Reviewers calculate net clear door width after deducting door stop and frame — a 30-inch pre-hung door (~27.5 inches net clear) is flagged even though some applicants assume nominal door size means compliance.",
    enforcementBehavior:
      "Net clear door width, not nominal door size, is used for compliance. A 30-inch door is consistently flagged; a 36-inch pre-hung door is the standard correction recommendation.",
    codeReference: "Section 101.4 (32-inch minimum net clear primary exit door width)",
    confidenceLevel: 0.9,
    evidenceCount: 1,
    patternType: "stricter_than_code",
    sourceCases: ["BPR-2024-0203"],
  },
];

export const PATTERN_COUNT = LEARNED_PATTERNS.length;
export const PATTERN_SOURCE_LETTER_COUNT = 10; // total letters analyzed
